spring.application.name=seedhope



# Database connection

spring.datasource.url=jdbc:postgresql://seedhope-seedhope.l.aivencloud.com:26816/defaultdb?sslmode=require
spring.datasource.username=avnadmin
spring.datasource.password= AVNS_qBSxcQMfJ-rnbf14k30
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# stripe api key
stripe.secret.key= sk_test_51QPkg6FJY7cbf1dBwVHoGGPPzwFucCI5e1ikCrCmYFNfEH1SXLnCrFjTQP6sLf6edcTqLyX3MEDLHoyi4CGCHlRe00SPVRqcDJ


# SSL Commerz Configuration
sslcommerz.store.id= seedh6772cef7a71ac
sslcommerz.store.password= seedh6772cef7a71ac@ssl
sslcommerz.api.url = https://sandbox.sslcommerz.com/gwprocess/v3/api.php


logging.level.org.springframework.web.client.RestTemplate=DEBUG
logging.level.org.apache.http=DEBUG

spring.web.resources.static-locations=file:///D:/SeedHope/Backend/seedhope/src/main/resources/photos/

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

api_base_url_android = http://192.168.0.106:8080
